name: crammy_app
description: "A Flutter learning and study app"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  camera: ^0.11.0+2
  cupertino_icons: ^1.0.8
  docx_to_text: ^1.0.1
  file_picker: ^8.1.4
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.4
  flutter_svg: ^2.0.10+1
  gap: ^3.0.1
  google_generative_ai: ^0.4.6
  intl: ^0.20.2
  linear_progress_bar: ^1.2.0
  path: ^1.9.1
  rename: ^3.1.0
  shared_preferences: ^2.5.4
  sqflite: ^2.4.2

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/images/appIconSmall.png"

flutter_native_splash:
  android: true
  ios: false

  color: "#7F9EF3"
  image: assets/images/appIcon.png

  android_12:
    color: "#7F9EF3"
    image: assets/images/appIconLarge.png

flutter:
  uses-material-design: true
  
  assets:
    - .env
    - assets/images/
    - assets/svg/


